### PR TITLE
Color labels - storage and display

### PR DESCRIPTION
**Pull request by jimallman**
OK, I've implemented these features [as you outlined them here](https://github.com/david-c14/SubmarineFree/issues/80#issuecomment-602177822). Here's a color-label rollover, and a preview of the "billboard" view, which might or might not be beefy enough to work at YouTube scale:
Screen Shot 2020-03-23 at 8 56 32 PM
Screen Shot 2020-03-23 at 8 56 43 PM

### CODE REVIEW

**Comment by jimallman** [comment]
I have noticed one odd thing -- when used in a patch, my WM-101 seems to block the ability to delete a module from the rack with the backspace/delete key. Oddly, this is broken for _all_ modules and not just this one. I'm guessing that I am somehow blocking a key event handler, but I can't see how.

When I update to your latest release, the problem is not there. When I restore mine, it returns. Thoughts?

**Comment by david-c14** [comment]
Off the top of my head, the only thing I can think of is that this is caused by the tooltip code.  I'm guessing that you copied some of that code from elsewhere. I'm working at the moment, so I'm not really free to investigate. 

If you figure out where SubTooltip was already in use, it's possible that that module also exhibits the problem. Most likely because I notice that e.consume is commented out in all that new code.

So it might be an existing problem in my plugin, but hasn't previously affected the WM-101.

I might be wrong, but I think SubTooltip was written for the DO-xxx devices.

**Comment by david-c14** [comment]
I've rebased these PRs again. As soon as I get a chance, I'm going to pull these into my codebase and work towards incorporating them into the release.

**Comment by jimallman** [comment]
> Most likely because I notice that e.consume is commented out in all that new code.

Good catch! I will look deeper into this as well. It's possible that this is blocking event bubbling or the like, keeping key and mouse events from reaching the main module.

**Comment by jimallman** [comment]
FYI, I've been testing previous versions of my branch, and it seems the culprit (breaking module deletion w/ backspace key) is [in this commit](https://github.com/jimallman/SubmarineFree/commit/a3baab94265d8017dd52abaa180c385431f3177b). Which is odd, since it seems harmless enough. I'll back up to the previous commit and make these changes in baby steps. That should narrow it down pretty quickly.

**Comment by david-c14** [comment]
OK. I've only added EventParamFields to menus before now.

**Comment by jimallman** [comment]
> Looks like toggling its `visible` property will do the trick; the hidden field doesn't capture keystrokes.

Not quite correct, it turns out. I'm using `addChild` and `removeChild` instead (see commit message for details). I think this is a solid fix!

**Comment by jimallman** [comment]
I've added one more tweak. The billboard view was a bit stark, so now it mimics a stack of cables:

Screen Shot 2020-03-24 at 9 07 52 PM

This uses a small tiling PNG that loads just once. I was worried about the CPU load, but it seems to have no (or negligible) effect in the CPU meter. In my testing, the billboard works well for up to eight or ten colors, which is more than you'd really want to use IMO:

Screen Shot 2020-03-24 at 9 11 47 PM

And now I'll stop tinkering! I just had to get that out of my system.  :bowtie:

**Comment by david-c14** [comment]
That's beautiful.

It's difficult for me to get time on this at the moment, with the disruption to life that we are suffering. But I hope to get this integrated soon.   I thought I would make a separate billboard as an option (keeping the integrated one as well) Because you could put the separate billboard into a patch to distribute, and it could show the colors you used in the patch, even without a wire manager. (if you include the wire manager in the patch, it will have the end-user's colors in it, not the original patch colors)   But if I can re-use the same code that's already there.

Stay safe.

**Comment by jimallman** [comment]
Glad you like it!

> if you include the wire manager in the patch, it will have the end-user's colors in it, not the original patch colors

Yeah, I finally made this connection when I woke up this morning (sigh). Now I understand why you were talking about a separate "static" billboard module.

I wonder if there could be a "freeze/thaw" option in WM-101 for this? Where in its "frozen" state it persists the current colors in the patch, and then "thaw" could restore normal WM-101 with the static colors as the working set (or possibly added to their stored collections using the current patch name).

**Comment by david-c14** [comment]
I think that would definitely violate the single responsibility principle. A standalone module should do that job.

**Pull request merged**
